export const seededGarages = [
    {
        id: 'garage_emulator_1',
        name: 'Downtown Garage',
        address: '100 Main St',
        latitude: 37.421998,
        longitude: -122.084,
        status: 'available',
        distanceMeters: 180,
        availableSpots: 42,
        totalSpots: 120,
        pricing: { hourly: 2.5, currency: 'EUR' },
    },
    {
        id: 'garage_shoreline_champion',
        name: 'Shoreline Parking',
        address: '1 Shoreline Blvd, Ruse',
        latitude: 43.852,
        longitude: 25.922,
        status: 'available',
        availableSpots: 24,
        totalSpots: 120,
        pricing: { hourly: 2.5, currency: 'EUR' },
        policies: { prepayRequired: false },
        features: { evChargers: 4, coveredParking: true, disabledAccess: true },
    },
    {
        id: 'garage_budget_champion',
        name: 'Budget Park & Save',
        address: '99 Saver St, Ruse',
        latitude: 43.8535,
        longitude: 25.921,
        status: 'available',
        availableSpots: 60,
        totalSpots: 200,
        pricing: { hourly: 0.5, currency: 'EUR' },
        policies: { prepayRequired: false },
        features: { evChargers: 2, coveredParking: false, disabledAccess: true },
    },
    {
        id: 'garage_tesla_hub_champion',
        name: 'Tesla Super-Hub',
        address: '500 EV Way, Ruse',
        latitude: 43.854,
        longitude: 25.9245,
        status: 'available',
        availableSpots: 45,
        totalSpots: 90,
        pricing: { hourly: 4.0, currency: 'EUR' },
        policies: { prepayRequired: true, overstayPenalty: 25 },
        features: { evChargers: 32, coveredParking: true, disabledAccess: true },
    },
    {
        id: 'garage_longstay_champion',
        name: 'Monthly Long-Stay',
        address: '12 Residency Ave, Ruse',
        latitude: 43.8512,
        longitude: 25.925,
        status: 'available',
        availableSpots: 80,
        totalSpots: 150,
        pricing: { hourly: 1.5, currency: 'EUR' },
        policies: { prepayRequired: false },
        features: { evChargers: 6, coveredParking: true, disabledAccess: true },
        maxTime: 43200,
    },
    {
        id: 'garage_downtown_central_champion',
        name: 'Downtown Central',
        address: '10 Central Sq, Ruse',
        latitude: 43.8525,
        longitude: 25.9235,
        status: 'limited',
        availableSpots: 2,
        totalSpots: 50,
        pricing: { hourly: 3.0, currency: 'EUR' },
        policies: { prepayRequired: true, overstayPenalty: 15 },
        features: { evChargers: 4, coveredParking: true, disabledAccess: true },
    },
    {
        id: 'garage_emulator_2',
        name: 'Shoreline Parking',
        address: '200 Shoreline Blvd',
        latitude: 37.4228,
        longitude: -122.0855,
        status: 'limited',
        distanceMeters: 350,
        availableSpots: 10,
        totalSpots: 80,
        pricing: { hourly: 3.0, currency: 'EUR' },
    },
];
