export const seededGarages = [
    {
        id: 'garage_emulator_1',
        name: 'Downtown Garage',
        address: '100 Main St',
        latitude: 37.421998,
        longitude: -122.084,
        status: 'available',
        distanceMeters: 180,
        availableSpots: 42,
        totalSpots: 120,
        pricing: { hourly: 2.5, currency: 'EUR' },
    },
    {
        id: 'garage_shoreline_champion',
        name: 'Shoreline Parking',
        address: '1 Shoreline Blvd, Ruse',
        latitude: 43.8505,
        longitude: 25.919,
        status: 'available',
        availableSpots: 26,
        totalSpots: 120,
        pricing: { hourly: 2.5, currency: 'EUR' },
        policies: { prepayRequired: false },
        features: { evChargers: 4, coveredParking: true, disabledAccess: true },
    },
    {
        id: 'garage_budget_champion',
        name: 'Budget Park & Save',
        address: '99 Saver St, Ruse',
        latitude: 43.8515,
        longitude: 25.9195,
        status: 'available',
        availableSpots: 60,
        totalSpots: 200,
        pricing: { hourly: 0.5, currency: 'EUR' },
        policies: { prepayRequired: false },
        features: { evChargers: 2, coveredParking: false, disabledAccess: true },
    },
    {
        id: 'garage_tesla_hub_champion',
        name: 'Tesla Super-Hub',
        address: '500 EV Way, Ruse',
        latitude: 43.853,
        longitude: 25.9215,
        status: 'available',
        availableSpots: 45,
        totalSpots: 90,
        pricing: { hourly: 4.0, currency: 'EUR' },
        policies: { prepayRequired: true, overstayPenalty: 25 },
        features: { evChargers: 32, coveredParking: true, disabledAccess: true, security: 'CCTV + Guard' },
    },
    {
        id: 'garage_airport_longstay_champion',
        name: 'Airport Long-Stay',
        address: '1 Terminal Rd, Ruse',
        latitude: 43.855,
        longitude: 25.926,
        status: 'available',
        availableSpots: 90,
        totalSpots: 200,
        pricing: { hourly: 1.5, currency: 'EUR' },
        policies: { prepayRequired: false },
        features: { evChargers: 8, coveredParking: true, disabledAccess: true },
        maxTime: 43200,
    },
    {
        id: 'garage_downtown_central_champion',
        name: 'Downtown Central',
        address: '10 Central Sq, Ruse',
        latitude: 43.8525,
        longitude: 25.9235,
        status: 'limited',
        availableSpots: 3,
        totalSpots: 100,
        pricing: { hourly: 3.0, currency: 'EUR' },
        policies: { prepayRequired: true, overstayPenalty: 15 },
        features: { evChargers: 4, coveredParking: true, disabledAccess: true },
    },
    {
        id: 'garage_maintenance_champion',
        name: 'Old Port Garage (Full)',
        address: '12 Harbor Rd, Ruse',
        latitude: 43.8495,
        longitude: 25.918,
        status: 'full',
        availableSpots: 0,
        totalSpots: 80,
        pricing: { hourly: 2.0, currency: 'EUR' },
        policies: { prepayRequired: false },
        features: { evChargers: 1, coveredParking: false, disabledAccess: false },
    },
    {
        id: 'garage_emulator_2',
        name: 'Shoreline Parking',
        address: '200 Shoreline Blvd',
        latitude: 37.4228,
        longitude: -122.0855,
        status: 'limited',
        distanceMeters: 350,
        availableSpots: 10,
        totalSpots: 80,
        pricing: { hourly: 3.0, currency: 'EUR' },
    },
];
